# Generated by Django 4.2.11 on 2024-11-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder_name', models.CharField(max_length=50)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
